### ISSUE TITLE
Incompatibility with open parties and claim mod

### ISSUE THREAD

**Issue by Anewri** [lanAnderson/SeasonHUD#26]
This mod conflicts with the open parties and claim mod, as a result it is not possible to see the information. This happens when you claim a chunk area and you are in that area.

![javaw_PnkvFYfR8u](https://user-images.githubusercontent.com/70771409/234857564-dfd52f29-aff6-4c4f-9552-472bd49bc8f6.png)

**Comment by lanAnderson** [comment]
Should be fixed in 1.4.14
