### ISSUE TITLE
Suggestion: Adding Config to move the hud on x and y axis - forge 1.19.2

### ISSUE THREAD

**Issue by celsiusqc** [lanAnderson/SeasonHUD#3]
Could you add a config option to move the hud on the x and y axis, and let us specify per entry (either the season logo or the text)
Also, 
Adding a config making it so you require us to have a calendar on us to show the hud / adding support with curios for when added in a curios slot?

**Comment by lanAnderson** [comment]
I added config options to offset the x and y of the HUD in update 1.3.2, it's uploading to CurseForge now

I'll look into the second part about an option to require the item, just didn't have time at the moment.
