### ISSUE TITLE
When in a claimed chunk with FTB Chunks installed, SeasonHUD overlaps with FTB Chunks minimap text

### ISSUE THREAD

**Issue by zlainsama** [lanAnderson/SeasonHUD#6]
![image](https://user-images.githubusercontent.com/3251859/216267288-ed4356d2-6953-461b-b1fc-eb4a4db68d02.png)
Versions:
- seasonhud-1.19.2-1.4.0
- ftb-chunks-forge-1902.3.15-build.233

**Comment by lanAnderson** [comment]
Thanks, I don't really use FTB Chunks, so I didn't account for that. Should be fixed in 1.4.1, that is uploading to CurseForge now.

**Comment by zlainsama** [comment]
![image](https://user-images.githubusercontent.com/3251859/216453234-f5b43856-6358-4b69-944d-fc21bd8bc8cc.png)
After leaving a claimed chunk or un-claiming the chunk, SeasonHUD text does not return to original position.

**Comment by lanAnderson** [comment]
Let me take another look and find another way of detecting it

**Comment by lanAnderson** [comment]
Okay should actually work this time. 1.4.2 is uploading on CurseForge now
