### ISSUE TITLE
[1.18.2 - Latest] SeasonHUD caused a crash upon loading into a world. 

### ISSUE THREAD

**Issue by Phweeeee** [lanAnderson/SeasonHUD#9]
It appears this is a crash due to the latest Xaero update.

Latest log: https://paste.gg/p/anonymous/7efef3f493cd42ddac37b2e6500c15a0

Crash report: https://paste.gg/p/anonymous/8ed7946094ed4bc2a5fbdccc6970a205

**Comment by lanAnderson** [comment]
Yeah, he changed the location the various options are stored. 

I have a fix for it ready, I just need to test a few things before I release it. It should be up soon though.

**Comment by lanAnderson** [comment]
Fixed in version 1.4.5 (ab6dfe9). 

Curseforge is having some issues at the moment, but I think I got it uploaded.
